name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v4
        # Fetch all history and tags
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: sudo apt-get install -y --no-install-recommends node-semver
      - uses: actions/setup-node@v6
        with:
          node-version: 20.x
      - name: Create release commit
      - run: |
          set -euo pipefail
          npm ci
          npm run build
          npm run test
          npm run generate-licenses
          cargo install cargo-about
          ./scripts/generate-rust-licenses
          git add -f dist LICENSE-3RD-PARTY-JAVASCRIPT LICENSE-3RD-PARTY-RUST
          git rm -rf .github
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --unset "http.https://github.com/.extraheader"
          git commit -m "Release $GITHUB_REF_NAME"
          git tag -f "$GITHUB_REF_NAME"
      - name: Push release branch and tag
        run: |
          set -euo pipefail
          git remote add release https://FrancisRussell:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/FrancisRussell/ferrous-actions.git
          git push -f release "HEAD:refs/heads/release/$GITHUB_REF_NAME"
          git push -f release "refs/tags/$GITHUB_REF_NAME"
      - name: Update branch `latest` to latest release
        run: |
          set -euo pipefail
          LATEST_TAG=$(semver $(git tag -l 'v*') | tail -n1)
          if [[ -n "$LATEST_TAG" ]]; then
            echo "Pushing tag $LATEST_TAG to branch latest..."
            git push -f release "refs/tags/$LATEST_TAG:refs/heads/latest"
          else
            echo "Failed to identify the latest release" >&2
            exit 1
          fi
